database:
  host: "{{DB_HOST}}"
  port: "{{DB_PORT}}"
  username: "{{DB_USER}}"
  password: "{{DB_PASSWORD}}"
  name: "{{DB_NAME}}"
  client: "{{DB_CLIENT}}"

application:
  port: 3000
  slack_webhook: "{{SLACK_URI}}"